version: '3.7'

services:
  app:
    image: documentstorage/documentstorage:${APP_IMAGE_VERSION}
    build: 
      context: .
      args:
        JAR_FILE: target/documentstorage-${APP_BUILD_VERSION}.jar
    environment:
    - MONGO_URI=mongodb://mymongodb/dockercompose
    - JAVA_OPTS=-Xms256m -Xmx256m -Dsun.net.inetaddr.ttl=5 -Xdebug -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:9094
    depends_on:
    - db
    networks:
      - mynetwork
    deploy:
      mode: replicated
      replicas: 3
    restart: always

  db:
    image: mongo:4.0.4
    volumes:
      - mongodb:/data/db
    networks:
      mynetwork:
        aliases:
          - "mymongodb"

  nginx:
    image: nginx:1.15-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./cert:/etc/ssl/cert:ro

    networks:
      - mynetwork
    depends_on:
      - app
    ports:
      - 443:443

networks:
  mynetwork:

volumes:
  mongodb: